version: '3.8'
services:
  algo-server:
    image: hoangtc125admin/algo:server
    ports:
      - 8001:8001
    volumes:
      - ./log:/algo/log
      - ../.env:/algo/.env
      - ../resources/algo-firebase.json:/algo/resources/algo-firebase.json
      - ../resources/cclub-cloud-vision-api.json:/algo/resources/cclub-cloud-vision-api.json
    network_mode: "host" # to test locally running service